---

server:
  port: 8081
  ssl:
    enabled: false
management:
  server:
    port: 8082
logging:
  level:
    com.craigrueda.gateway.core.handler: INFO
    #com.craigrueda.gateway.core.filter.route.WebClientRoutingFilter: TRACE
gateway:
  sensitiveClientResponseHeaders:
    - server
  routes:
    - url: http://httpbin.org
      path: /test/**
      stripPrefix: true
      sensitiveClientResponseHeaders:
        - via
