---

server:
  port: 8081
  ssl:
    enabled: false
management:
  server:
    port: 8082
logging:
  level:
    com.craigrueda.gateway.core.handler: INFO
    #com.craigrueda.gateway.core.filter.route.WebClientRoutingFilter: TRACE
gateway:
  addForwardedHeaders: true
  enabled: true
  preserveHostHeader: false
  sensitiveClientResponseHeaders:
    - server
  routes:
    - url: http://192.168.99.100
      path: /test/**
      stripPrefix: true
      sensitiveClientResponseHeaders:
        - via
    - url: http://192.168.99.100
      path: /post/**
    - url: https://craig.craigrueda.com:4430
      path: /local-https/**
      stripPrefix: true
    - url: http://craig.craigrueda.com:8000
      path: /local-http/**
      stripPrefix: true
    - url: ws://craig.craigrueda.com:8080
      path: /ws/**
      stripPrefix: true
  upstreamHttp:
    maxPerRouteConnections: 100
    useEpoll: true
    ssl:
      useOpenSSL: true
  upstreamWs:
    maxPerRouteConnections: -1
    ssl:
      useOpenSSL: true
